# Generated by Django 2.0 on 2017-12-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosPosible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(default='UserDummy', max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('permisos', models.TextField(blank=True, null=True)),
                ('is_staff', models.IntegerField(blank=True, null=True)),
                ('is_superuser', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('fecha_alta', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'usuarios_posible',
            },
        ),
        migrations.CreateModel(
            name='CodigosPostales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=250, null=True)),
                ('id_municipio', models.IntegerField(blank=True, null=True)),
                ('municipio', models.CharField(blank=True, max_length=250, null=True)),
                ('id_ciudad', models.IntegerField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=250, null=True)),
                ('id_asentamiento', models.IntegerField(blank=True, null=True)),
                ('asentamiento', models.CharField(blank=True, max_length=250, null=True)),
                ('id_asentamiento_tipo', models.IntegerField(blank=True, null=True)),
                ('asentamiento_tipo', models.CharField(blank=True, max_length=250, null=True)),
                ('zona', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'codigos_postales',
            },
        ),
        migrations.CreateModel(
            name='Configs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'configs',
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'estados',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=250, null=True)),
                ('sitio', models.CharField(max_length=20)),
                ('evento', models.CharField(blank=True, max_length=250, null=True)),
                ('datos', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'logs',
            },
        ),
        migrations.CreateModel(
            name='Newletters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter_html', models.TextField()),
                ('newsletter_title', models.CharField(max_length=255)),
                ('newsletter_segments', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'newletters',
            },
        ),
        migrations.CreateModel(
            name='Referencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('referencia', models.CharField(blank=True, max_length=20, null=True)),
                ('sitio', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'referencias',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('email_alt', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('is_staff', models.IntegerField(blank=True, null=True)),
                ('is_superuser', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('fecha_alta', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('id_emprendedor', models.IntegerField(blank=True, null=True)),
                ('id_alumno', models.IntegerField(blank=True, null=True)),
                ('uuid', models.CharField(blank=True, max_length=250, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('id_municipio', models.IntegerField(blank=True, null=True)),
                ('municipio', models.CharField(blank=True, max_length=250, null=True)),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=10, null=True)),
                ('profesion', models.CharField(blank=True, max_length=250, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('empresa', models.CharField(blank=True, max_length=250, null=True)),
                ('giro', models.CharField(blank=True, max_length=250, null=True)),
                ('puesto', models.CharField(blank=True, max_length=250, null=True)),
                ('maximo_grado', models.CharField(blank=True, max_length=250, null=True)),
                ('escuela', models.CharField(blank=True, max_length=250, null=True)),
                ('socios', models.TextField(blank=True, null=True)),
                ('tel_1_lada', models.CharField(blank=True, max_length=10, null=True)),
                ('tel_1', models.CharField(blank=True, max_length=250, null=True)),
                ('tel_2_lada', models.CharField(blank=True, max_length=10, null=True)),
                ('tel_2', models.CharField(blank=True, max_length=250, null=True)),
                ('tel_casa_lada', models.IntegerField(blank=True, null=True)),
                ('tel_casa', models.CharField(blank=True, max_length=250, null=True)),
                ('tel_of_lada', models.IntegerField(blank=True, null=True)),
                ('tel_of', models.CharField(blank=True, max_length=250, null=True)),
                ('tel_cel_lada', models.IntegerField(blank=True, null=True)),
                ('tel_cel', models.CharField(blank=True, max_length=250, null=True)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
                ('como_te_enteraste_old', models.CharField(blank=True, max_length=250, null=True)),
                ('como_te_enteraste', models.CharField(blank=True, max_length=250, null=True)),
                ('fb_uid', models.CharField(blank=True, max_length=250, null=True)),
                ('fb_uid_pplus', models.CharField(blank=True, max_length=250, null=True)),
                ('li_uid', models.CharField(blank=True, max_length=250, null=True)),
                ('url_perfil_facebook', models.CharField(blank=True, max_length=250, null=True)),
                ('url_perfil_linkedin', models.CharField(blank=True, max_length=250, null=True)),
                ('codigo_seguridad', models.CharField(blank=True, max_length=8, null=True)),
                ('metodo_alta', models.CharField(blank=True, max_length=100, null=True)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_alta', models.CharField(blank=True, max_length=250, null=True)),
                ('ind_emprend', models.IntegerField(blank=True, null=True)),
                ('porcentaje_perfil', models.IntegerField(blank=True, null=True)),
                ('email_activacion', models.IntegerField(blank=True, null=True)),
                ('newsletter', models.IntegerField(blank=True, null=True)),
                ('newsletter_segments', models.CharField(blank=True, max_length=13, null=True)),
                ('inversiones', models.IntegerField(blank=True, null=True)),
                ('rendimientos', models.IntegerField(blank=True, null=True)),
                ('intereses_categorias', models.CharField(blank=True, max_length=300, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
