# Generated by Django 2.0 on 2018-01-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posible_login_reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(default='usuarios/no-img.jpg', null=True, upload_to=''),
        ),
    ]
