# Generated by Django 2.0 on 2018-01-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posible_login_reg', '0002_auto_20180101_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(default='usuarios/no-img.png', null=True, upload_to=''),
        ),
    ]
